### ISSUE TITLE
Network error, the server could be down or you are not permitted to access this resource.

### ISSUE THREAD

**Issue by saybertevgeny** [mjstewart/fakesmtp-web#1]
Why? My compose

  ```
fakedsmtp:
    image: munkyboy/fakesmtp
    container_name: fake-smtp
    ports: 
      - 25:25
    volumes:
      - ./fake-smtp-emails:/var/mail
    networks:
      - backend
      - frontend
      
  fakesmtpweb:
    image: mjstewart/fakesmtp-web:1.0
    container_name: fake-smtp-web
    ports: 
      - 60500:8080
    volumes:
      - ./fake-smtp-emails:/var/mail
    environment:
      - EMAIL_INPUT_DIR_POLL_RATE_SECONDS=10
    depends_on:
      - fakedsmtp
    networks:
      - backend
      - frontend

```
